export const PERMISSION_MAP = {
    BASIC_INFO_VIEW: "BASIC_INFO_VIEW",
    BASIC_INFO_EDIT: "BASIC_INFO_EDIT",
    AVATAR_VIEW: "AVATAR_VIEW",
    AVATAR_EDIT: "AVATAR_VIEW",
    EXPERIENCE_VIEW: "EXPERIENCE_VIEW",
    EXPERIENCE_EDIT: "EXPERIENCE_EDIT",
    SUMMARY_EDIT: "SUMMARY_EDIT",
    SUMMARY_VIEW: "SUMMARY_VIEW",
};
export const PERMISSION = Object.keys(PERMISSION_MAP);
